import Head from "next/head";
import Layout from "@/components/Layout";
import ContactForm from "@/components/forms/ContactForm";
import Heading from "@/components/Heading";
import { sendEmail } from "@/lib/api-functions/client";
export default function Contact() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Heading>Contact</Heading>
        <ContactForm submitHandler={sendEmail} />
      </Layout>
    </>
  );
}
